version: '2.1'

services:
  search-service:
    image: search-service
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5001:5001
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js